-- ============================================================
-- Migration : 015_referral_system
-- Description: Implements the peer-referral reward system.
--              Adds referral tracking columns to public.users,
--              creates an immutable audit table (referral_events),
--              and exposes a single atomic RPC
--              (award_referral_bonus_txn) for the bot/edge layer.
--
-- Security model
--   - referral_events is readable only by the referrer and the
--     referee via RLS; anon has zero access.
--   - The RPC is SECURITY DEFINER so it can credit both user
--     balances and write the audit row without exposing the
--     underlying tables to the caller.
--   - EXECUTE is revoked from PUBLIC, anon, and authenticated;
--     only the service role (bot / edge functions) may call the
--     function directly. Frontend clients reach it through the
--     bot gateway only.
--   - The idempotency guard (UNIQUE constraint on referee_id in
--     referral_events + ON CONFLICT DO NOTHING inside the RPC)
--     makes repeated invocations safe: each referee can only
--     trigger one payout, ever.
--
-- Lock ordering (canonical — see docs/LOCK_ORDERING.md)
--   award_referral_bonus_txn locks two rows from the same table
--   (users), both at canonical position 2. When two rows from
--   the same table are locked in a single transaction, the
--   deadlock risk is between concurrent calls where T1 holds
--   row A and waits for row B while T2 holds row B and waits
--   for row A. This is prevented by always locking the
--   lower-UUID row first (alphabetical / bytewise order on the
--   UUID text representation). The ordering is documented in the
--   RPC header comment and in the RPC Lock Acquisition Table
--   update at the bottom of this file.
--
--   Full canonical sequence for award_referral_bonus_txn:
--     1. users FOR UPDATE  (lower  UUID — canonical position 2a)
--     2. users FOR UPDATE  (higher UUID — canonical position 2b)
--
-- Depends on : 001_initial_schema (public.users),
--              008_daily_rewards  (no structural dep, style ref)
-- Idempotent  : NO — run exactly once.
-- Rollback    : see Down section at the bottom of this file.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Section 1 — Extend public.users with referral columns
-- ------------------------------------------------------------

ALTER TABLE public.users
  ADD COLUMN referral_code          TEXT         UNIQUE,
  ADD COLUMN referred_by            UUID         REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN referral_code_used     TEXT,
  ADD COLUMN referral_bonus_earned  NUMERIC(18,4) NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.users.referral_code IS
  'Unique invite code assigned to the user (generated by the bot '
  'on first request). NULL until the user first requests their code.';

COMMENT ON COLUMN public.users.referred_by IS
  'FK to the user who referred this account. Set once at registration '
  'time; immutable after the referral bonus has been paid. '
  'NULL means the user joined without a referral code.';

COMMENT ON COLUMN public.users.referral_bonus_earned IS
  'Running total of referral bonus tokens earned as a referrer. '
  'Incremented atomically by award_referral_bonus_txn.';

-- Partial unique index for code lookups (the ALTER TABLE UNIQUE
-- constraint covers the full column; this partial index additionally
-- ensures the planner can use an index skip on NULL rows, which
-- are the majority until codes are generated).
CREATE UNIQUE INDEX idx_users_referral_code
  ON public.users (referral_code)
  WHERE referral_code IS NOT NULL;

-- Sparse index for "show me everyone I referred" queries.
CREATE INDEX idx_users_referred_by
  ON public.users (referred_by)
  WHERE referred_by IS NOT NULL;

-- ------------------------------------------------------------
-- Section 2 — Audit / history table: public.referral_events
--
-- Append-only. One row per referee_id (enforced by UNIQUE
-- constraint). The constraint is the authoritative idempotency
-- guard; the RPC uses ON CONFLICT DO NOTHING as a second layer.
-- ------------------------------------------------------------

CREATE TABLE public.referral_events (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id     UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  referee_id      UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  referrer_bonus  NUMERIC(18,4) NOT NULL DEFAULT 500
                                CHECK (referrer_bonus >= 0),
  referee_bonus   NUMERIC(18,4) NOT NULL DEFAULT 500
                                CHECK (referee_bonus  >= 0),
  bonus_paid_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  -- Core idempotency: every referee may only generate one payout event, ever.
  CONSTRAINT referral_events_referee_unique UNIQUE (referee_id)
);

COMMENT ON TABLE public.referral_events IS
  'Immutable record of every referral bonus payout. One row per '
  'referee. Used for audit, leaderboards, and idempotency enforcement.';

COMMENT ON COLUMN public.referral_events.referrer_bonus IS
  'Tokens credited to the referrer for this event (default 500).';
COMMENT ON COLUMN public.referral_events.referee_bonus IS
  'Tokens credited to the new user (referee) for this event (default 500).';
COMMENT ON COLUMN public.referral_events.bonus_paid_at IS
  'Wall-clock timestamp (UTC) when the bonus transaction committed.';

-- Referrer history: "how many people have I recruited?"
CREATE INDEX idx_referral_events_referrer
  ON public.referral_events (referrer_id);

-- ------------------------------------------------------------
-- Section 3 — Row Level Security on public.referral_events
-- ------------------------------------------------------------

ALTER TABLE public.referral_events ENABLE ROW LEVEL SECURITY;

-- Both parties may read events in which they participated.
CREATE POLICY "referral_events: participants can select"
  ON public.referral_events
  FOR SELECT
  TO authenticated
  USING (auth.uid() = referrer_id OR auth.uid() = referee_id);

-- No INSERT / UPDATE / DELETE policies for authenticated users:
-- writes happen exclusively through the SECURITY DEFINER RPC.
REVOKE ALL ON public.referral_events FROM anon;

-- ------------------------------------------------------------
-- Section 4 — RPC: award_referral_bonus_txn
--
-- Caller   : service_role (bot / edge function only)
-- Args     : p_referrer_id   UUID    — the user who owns the referral code
--            p_referee_id    UUID    — the newly registered user
--            p_referrer_bonus NUMERIC — tokens for the referrer  (default 500)
--            p_referee_bonus  NUMERIC — tokens for the referee   (default 500)
-- Returns  : JSONB with the following keys:
--              already_paid        BOOLEAN
--              referrer_new_balance NUMERIC  (unchanged if already_paid)
--              referee_new_balance  NUMERIC  (unchanged if already_paid)
--              referrer_bonus       NUMERIC  (0 if already_paid)
--              referee_bonus        NUMERIC  (0 if already_paid)
--
-- Atomicity guarantee:
--   Both balance credits and the audit row are written inside a
--   single implicit transaction. The FOR UPDATE locks on both
--   user rows prevent double-spend under concurrent calls.
--
-- Idempotency guarantee:
--   If referral_events already contains a row for p_referee_id
--   the function returns {already_paid: true} without mutating
--   any balances. The ON CONFLICT DO NOTHING on the INSERT
--   provides a second-layer guard for races that pass the
--   initial check simultaneously.
--
-- Lock ordering (see docs/LOCK_ORDERING.md):
--   Both locks are on public.users (canonical position 2).
--   To prevent intra-table deadlocks, the lower UUID (lexicographic
--   bytewise comparison) is always locked first.
--
--   Lock order (canonical):
--     1. users FOR UPDATE  (MIN(p_referrer_id, p_referee_id) — position 2a)
--     2. users FOR UPDATE  (MAX(p_referrer_id, p_referee_id) — position 2b)
--
-- Human-only guard:
--   Bot accounts (is_human = FALSE) are rejected as both referrer
--   and referee so bots cannot farm the bonus system.
--
-- Outbox event:
--   On a successful new payout the function inserts a row into
--   event_outbox so the achievement checker / notification worker
--   can react asynchronously without coupling to this transaction.
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.award_referral_bonus_txn(
  p_referrer_id    UUID,
  p_referee_id     UUID,
  p_referrer_bonus NUMERIC(18,4) DEFAULT 500,
  p_referee_bonus  NUMERIC(18,4) DEFAULT 500
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_first_lock_id  UUID;
  v_second_lock_id UUID;
  v_referrer       RECORD;
  v_referee        RECORD;
  v_already_paid   BOOLEAN := FALSE;
BEGIN
  -- --------------------------------------------------------
  -- 0. Validate arguments.
  -- --------------------------------------------------------
  IF p_referrer_id = p_referee_id THEN
    RAISE EXCEPTION 'Referrer and referee must be different users';
  END IF;

  IF p_referrer_bonus < 0 OR p_referee_bonus < 0 THEN
    RAISE EXCEPTION 'Bonus amounts must be non-negative';
  END IF;

  -- --------------------------------------------------------
  -- 1. Determine lock order: always lock the lower UUID first
  --    to prevent intra-table deadlocks when two concurrent
  --    calls involve the same pair in opposite roles.
  -- --------------------------------------------------------
  IF p_referrer_id < p_referee_id THEN
    v_first_lock_id  := p_referrer_id;
    v_second_lock_id := p_referee_id;
  ELSE
    v_first_lock_id  := p_referee_id;
    v_second_lock_id := p_referrer_id;
  END IF;

  -- --------------------------------------------------------
  -- 2. Acquire lock on the lower-UUID row (position 2a).
  --    We must then re-fetch into the correctly named variable.
  -- --------------------------------------------------------
  IF v_first_lock_id = p_referrer_id THEN
    SELECT id, is_human, balance, referral_bonus_earned, display_name
    INTO   v_referrer
    FROM   public.users
    WHERE  id = p_referrer_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Referrer % not found', p_referrer_id;
    END IF;

    -- --------------------------------------------------------
    -- 3a. Acquire lock on the higher-UUID row (position 2b).
    -- --------------------------------------------------------
    SELECT id, is_human, balance, display_name
    INTO   v_referee
    FROM   public.users
    WHERE  id = p_referee_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Referee % not found', p_referee_id;
    END IF;
  ELSE
    -- Referee UUID is lower; lock it first (position 2a).
    SELECT id, is_human, balance, display_name
    INTO   v_referee
    FROM   public.users
    WHERE  id = p_referee_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Referee % not found', p_referee_id;
    END IF;

    -- --------------------------------------------------------
    -- 3b. Acquire lock on the higher-UUID row (position 2b).
    -- --------------------------------------------------------
    SELECT id, is_human, balance, referral_bonus_earned, display_name
    INTO   v_referrer
    FROM   public.users
    WHERE  id = p_referrer_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Referrer % not found', p_referrer_id;
    END IF;
  END IF;

  -- --------------------------------------------------------
  -- 4. Human-only guard: reject bot accounts on both sides.
  -- --------------------------------------------------------
  IF NOT v_referrer.is_human THEN
    RAISE EXCEPTION 'Referrer % is not a human account', p_referrer_id;
  END IF;

  IF NOT v_referee.is_human THEN
    RAISE EXCEPTION 'Referee % is not a human account', p_referee_id;
  END IF;

  -- --------------------------------------------------------
  -- 5. Idempotency check: has this referee already triggered
  --    a payout? Both locks are held, so this read is stable.
  -- --------------------------------------------------------
  IF EXISTS (
    SELECT 1 FROM public.referral_events WHERE referee_id = p_referee_id
  ) THEN
    RETURN jsonb_build_object(
      'already_paid',          TRUE,
      'referrer_new_balance',  v_referrer.balance,
      'referee_new_balance',   v_referee.balance,
      'referrer_bonus',        0,
      'referee_bonus',         0
    );
  END IF;

  -- --------------------------------------------------------
  -- 6. Credit balances for both parties.
  -- --------------------------------------------------------
  UPDATE public.users
  SET
    balance               = balance + p_referrer_bonus,
    referral_bonus_earned = referral_bonus_earned + p_referrer_bonus
  WHERE id = p_referrer_id;

  UPDATE public.users
  SET balance = balance + p_referee_bonus
  WHERE id = p_referee_id;

  -- --------------------------------------------------------
  -- 7. Write the audit record. ON CONFLICT DO NOTHING provides
  --    a second idempotency layer for the rare race where two
  --    concurrent calls both passed step 5 before either
  --    committed.
  -- --------------------------------------------------------
  INSERT INTO public.referral_events
    (referrer_id, referee_id, referrer_bonus, referee_bonus)
  VALUES
    (p_referrer_id, p_referee_id, p_referrer_bonus, p_referee_bonus)
  ON CONFLICT (referee_id) DO NOTHING;

  -- --------------------------------------------------------
  -- 8. Publish outbox event for achievement checker and
  --    notification worker (eventual consistency).
  -- --------------------------------------------------------
  INSERT INTO public.event_outbox (event_type, payload)
  VALUES (
    'referral_bonus_paid',
    jsonb_build_object(
      'referrer_id',    p_referrer_id,
      'referee_id',     p_referee_id,
      'referrer_bonus', p_referrer_bonus,
      'referee_bonus',  p_referee_bonus
    )
  );

  -- --------------------------------------------------------
  -- 9. Return result with updated balances.
  -- --------------------------------------------------------
  RETURN jsonb_build_object(
    'already_paid',          FALSE,
    'referrer_new_balance',  v_referrer.balance + p_referrer_bonus,
    'referee_new_balance',   v_referee.balance  + p_referee_bonus,
    'referrer_bonus',        p_referrer_bonus,
    'referee_bonus',         p_referee_bonus
  );
END;
$$;

-- Revoke broad default execute privilege; grant to service_role only.
REVOKE EXECUTE ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) FROM anon;
REVOKE EXECUTE ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) FROM authenticated;
GRANT  EXECUTE ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) TO service_role;

COMMENT ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) IS
  'Atomic referral bonus payout. Acquires FOR UPDATE locks on both user '
  'rows in UUID-ascending order to prevent intra-table deadlocks, checks '
  'idempotency via referral_events.referee_id UNIQUE constraint, credits '
  'both balances, writes an audit row, and emits an event_outbox entry. '
  'Returns JSONB: {already_paid, referrer_new_balance, referee_new_balance, '
  'referrer_bonus, referee_bonus}. Callable by service_role only. '
  'Rejects bot accounts on both sides.';

-- ------------------------------------------------------------
-- RPC Lock Acquisition Table update (docs/LOCK_ORDERING.md)
--
-- | RPC                        | Migration | Lock 1               | Lock 2               |
-- |----------------------------|-----------|----------------------|----------------------|
-- | award_referral_bonus_txn   | 015       | users FOR UPDATE     | users FOR UPDATE     |
-- |                            |           | (lower UUID first — position 2a) | (higher UUID — position 2b) |
--
-- Deadlock analysis vs. existing RPCs:
--   - vs. execute_trade_txn   : both lock users; execute_trade_txn locks one
--     users row then inserts into trades. award_referral_bonus_txn never
--     touches trades. No shared second lock → no cycle possible.
--   - vs. close_trade_txn     : close_trade_txn locks one users row then one
--     trades row. award_referral_bonus_txn never touches trades. No cycle.
--   - vs. liquidate_trade_txn : same argument as close_trade_txn. No cycle.
--   - vs. join_tournament_txn : locks tournaments then one users row.
--     award_referral_bonus_txn never touches tournaments. No cycle.
--   - vs. settle_tournament_txn: locks only tournaments. No shared table. No cycle.
--   - vs. award_daily_reward_txn: locks one users row. award_referral_bonus_txn
--     locks two users rows in ascending UUID order. If award_daily_reward_txn
--     holds row A and award_referral_bonus_txn is waiting for row A (having
--     already locked row B, which is lower), that means row B < row A.
--     award_referral_bonus_txn locked B first (correct order) and is now
--     waiting for A. award_daily_reward_txn holds A and will complete without
--     waiting for B. No cycle.
--   - vs. itself (two concurrent calls for overlapping pairs): both calls
--     lock the lower UUID first. If T1 holds row X (lower) and T2 wants row X,
--     T2 waits for T1 to release X. T1 then locks row Y (higher) and completes.
--     No cycle.
-- ------------------------------------------------------------

COMMIT;

-- ============================================================
-- Down (rollback — execute manually, never in CI)
-- ============================================================
-- REVOKE EXECUTE ON FUNCTION public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC) FROM service_role;
-- DROP FUNCTION  IF EXISTS public.award_referral_bonus_txn(UUID, UUID, NUMERIC, NUMERIC);
-- DROP TABLE     IF EXISTS public.referral_events;
-- ALTER TABLE public.users
--   DROP COLUMN IF EXISTS referral_code,
--   DROP COLUMN IF EXISTS referred_by,
--   DROP COLUMN IF EXISTS referral_bonus_earned;
-- ============================================================
