-- =============================================================================
-- Migration: 021_tournament_codes
-- Description: Tournament entry codes (redemption system).
--
--   Codes are generated by admin (SQL Editor) and distributed to users
--   who paid or earned free entries via referrals.
--   Each code is single-use and tied to a specific tournament (or global).
--
-- Flow:
--   1. Admin generates codes in SQL Editor
--   2. User enters code in the tournaments page
--   3. redeem_tournament_code_txn validates and marks code as used
--   4. User is auto-joined to the tournament
-- =============================================================================

BEGIN;

CREATE TABLE public.tournament_codes (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  code          TEXT        NOT NULL UNIQUE,
  -- NULL tournament_id = global code (works for any tournament)
  tournament_id UUID        REFERENCES public.tournaments(id) ON DELETE SET NULL,
  created_by    TEXT        NOT NULL DEFAULT 'admin',
  used_by       UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  used_at       TIMESTAMPTZ,
  expires_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Code type: 'paid' (user paid), 'referral' (earned via referrals), 'promo' (giveaway)
  code_type     TEXT        NOT NULL DEFAULT 'paid'
                CHECK (code_type IN ('paid', 'referral', 'promo'))
);

CREATE INDEX idx_tournament_codes_code ON public.tournament_codes (code);
CREATE INDEX idx_tournament_codes_unused ON public.tournament_codes (tournament_id) WHERE used_by IS NULL;
CREATE INDEX idx_tournament_codes_user ON public.tournament_codes (used_by) WHERE used_by IS NOT NULL;

-- RLS
ALTER TABLE public.tournament_codes ENABLE ROW LEVEL SECURITY;

-- Users can see their own redeemed codes
CREATE POLICY "tournament_codes: owner can see used codes"
  ON public.tournament_codes FOR SELECT TO authenticated
  USING (auth.uid() = used_by);

REVOKE ALL ON public.tournament_codes FROM anon;
GRANT ALL ON public.tournament_codes TO service_role;

-- =============================================================================
-- RPC: redeem_tournament_code_txn
-- =============================================================================
-- Atomically redeems a code and joins the user to the tournament.
--
-- Lock order: users (pos 2) → tournament_codes (new, pos 6)
--
-- Steps:
--   1. Look up code (case-insensitive)
--   2. Validate: not already used, not expired
--   3. Lock user row
--   4. If code has tournament_id: validate tournament is joinable
--   5. Mark code as used
--   6. Join tournament (insert tournament_participants with balance snapshot)
--   7. Return result
-- =============================================================================

CREATE OR REPLACE FUNCTION public.redeem_tournament_code_txn(
  p_user_id UUID,
  p_code    TEXT,
  p_tournament_id UUID DEFAULT NULL  -- override if code is global
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code_row    RECORD;
  v_tournament  RECORD;
  v_user        RECORD;
  v_target_tournament_id UUID;
  v_participant JSONB;
BEGIN
  -- Step 1: Find the code (case-insensitive)
  SELECT * INTO v_code_row
  FROM public.tournament_codes
  WHERE UPPER(code) = UPPER(TRIM(p_code))
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'invalid_code', 'message', 'Invalid code.');
  END IF;

  -- Step 2: Check if already used
  IF v_code_row.used_by IS NOT NULL THEN
    RETURN jsonb_build_object('error', 'already_used', 'message', 'This code has already been used.');
  END IF;

  -- Step 3: Check expiry
  IF v_code_row.expires_at IS NOT NULL AND v_code_row.expires_at < NOW() THEN
    RETURN jsonb_build_object('error', 'expired', 'message', 'This code has expired.');
  END IF;

  -- Step 4: Determine target tournament
  v_target_tournament_id := COALESCE(v_code_row.tournament_id, p_tournament_id);

  IF v_target_tournament_id IS NULL THEN
    RETURN jsonb_build_object('error', 'no_tournament', 'message', 'Please select a tournament to join.');
  END IF;

  -- Step 5: Lock user row (canonical pos 2)
  SELECT * INTO v_user
  FROM public.users
  WHERE id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'user_not_found', 'message', 'User not found.');
  END IF;

  -- Step 6: Validate tournament
  SELECT * INTO v_tournament
  FROM public.tournaments
  WHERE id = v_target_tournament_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'tournament_not_found', 'message', 'Tournament not found.');
  END IF;

  IF v_tournament.status NOT IN ('upcoming', 'active') THEN
    RETURN jsonb_build_object('error', 'tournament_closed', 'message', 'This tournament is no longer accepting entries.');
  END IF;

  -- Step 7: Mark code as used
  UPDATE public.tournament_codes
  SET used_by = p_user_id, used_at = NOW()
  WHERE id = v_code_row.id;

  -- Step 8: Join tournament (snapshot balance)
  INSERT INTO public.tournament_participants (tournament_id, user_id, entry_balance)
  VALUES (v_target_tournament_id, p_user_id, v_user.balance)
  ON CONFLICT (tournament_id, user_id) DO NOTHING;

  -- Step 9: Return success
  RETURN jsonb_build_object(
    'success', TRUE,
    'tournament_id', v_target_tournament_id,
    'tournament_name', v_tournament.name,
    'code_type', v_code_row.code_type
  );
END;
$$;

REVOKE ALL ON FUNCTION public.redeem_tournament_code_txn FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_tournament_code_txn FROM anon;
REVOKE ALL ON FUNCTION public.redeem_tournament_code_txn FROM authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_tournament_code_txn TO service_role;

COMMIT;

-- =============================================================================
-- ADMIN HELPER: Generate batch codes
-- =============================================================================
-- Run in SQL Editor to generate codes for a tournament:
--
-- -- Generate 20 paid codes for a specific tournament
-- INSERT INTO public.tournament_codes (code, tournament_id, code_type)
-- SELECT
--   'ALPHA-' || UPPER(SUBSTR(MD5(RANDOM()::TEXT), 1, 4)) || '-' || UPPER(SUBSTR(MD5(RANDOM()::TEXT), 1, 4)),
--   'YOUR-TOURNAMENT-UUID-HERE',
--   'paid'
-- FROM generate_series(1, 20);
--
-- -- Generate 5 global promo codes (any tournament)
-- INSERT INTO public.tournament_codes (code, code_type)
-- SELECT
--   'PROMO-' || UPPER(SUBSTR(MD5(RANDOM()::TEXT), 1, 4)) || '-' || UPPER(SUBSTR(MD5(RANDOM()::TEXT), 1, 4)),
--   'promo'
-- FROM generate_series(1, 5);
--
-- -- View unused codes
-- SELECT code, code_type, tournament_id FROM public.tournament_codes WHERE used_by IS NULL;
-- =============================================================================
